#!/usr/bin/env python3
# Generated by _aitna/akmon/bin/sync.py. Do not edit this file by hand.
"""Claude PreToolUse wrapper for the akmon D2 ledger reminder.

Reminds once per session when an edit lands on a project-declared D2-sensitive path
(``[d2_ledger] sensitive_paths`` in ``<aitna>/.akmon.toml``) so the change gets logged in the
ledger for owner verification (design meta/design/d2-ledger.md §2.2, phase 2 of C11). The decision
logic lives in ``hook_core.py``; this entrypoint only adapts Claude Code's payload. Advisory only —
on any failure it logs to stderr and exits cleanly, never blocking the edit.
"""

from __future__ import annotations

import sys

from claude_adapter import load_payload, normalize_tool, print_result
from hook_core import d2_ledger_reminder_result


def main() -> int:
    try:
        payload = load_payload()
        tool_input = payload.get("tool_input") or {}
        session_id = payload.get("session_id")
        print_result(
            d2_ledger_reminder_result(
                normalize_tool(str(payload.get("tool_name") or "")),
                tool_input.get("file_path"),
                session_id if isinstance(session_id, str) else None,
            )
        )
    except Exception as exc:
        print(f"akmon d2-ledger-reminder hook: {type(exc).__name__}: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
