#!/usr/bin/env python3
# Generated by _aitna/akmon/bin/sync.py. Do not edit this file by hand.
"""Claude PreToolUse wrapper for the akmon delegation nudge.

Counts consecutive orchestrator edit/shell calls since session start or the last subagent
delegation (``Task``/``Agent`` resets the counter and re-arms the reminder) and, past the
threshold, injects a soft reminder — once per drift episode — that the work may belong to
a ``k-*`` delegate (MODEL.md § Capability tiers). Below the ask threshold, advisory only —
nothing is blocked; past it, a hard ``ask`` fires and escalates to ``deny`` outside the
interactive default permission mode (C31/D2-10 — an unattended ``ask`` was observed to be a
silent no-op). This fires only for main-chain calls: a subagent call (detected via the payload's
``agent_id``, present only inside a subagent) is exempt, since Claude Code shares the
``session_id`` between the main chain and its subagents and a k-* delegate has no ``Task``
tool to act on the nudge anyway. The decision logic lives in ``hook_core.py``; this
entrypoint only adapts Claude Code's payload.
"""

from __future__ import annotations

import sys

from claude_adapter import load_payload, normalize_tool, print_result
from hook_core import SHELL_TOOL, SUBAGENT_TOOL, delegation_nudge_result

# Claude tool names → the neutral kinds hook_core expects (edit tools via normalize_tool).
_TOOL_KINDS = {"Bash": SHELL_TOOL, "Task": SUBAGENT_TOOL, "Agent": SUBAGENT_TOOL}


def main() -> int:
    # Never block a tool call: on any failure, log to stderr and exit cleanly.
    try:
        payload = load_payload()
        name = str(payload.get("tool_name") or "")
        kind = _TOOL_KINDS.get(name) or normalize_tool(name)
        session_id = payload.get("session_id")
        is_subagent = bool(payload.get("agent_id"))
        sid = session_id if isinstance(session_id, str) else None
        permission_mode = payload.get("permission_mode")
        print_result(
            delegation_nudge_result(
                kind,
                sid,
                is_subagent=is_subagent,
                permission_mode=permission_mode if isinstance(permission_mode, str) else None,
            )
        )
    except Exception as exc:
        print(f"akmon delegation-nudge hook: {type(exc).__name__}: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
