#!/usr/bin/env python3
# Generated by _aitna/akmon/bin/sync.py. Do not edit this file by hand.
"""Claude PreToolUse wrapper: log each subagent delegation at zero token cost.

Appends one TSV line (timestamp, session_id, subagent, model, zone, description) to
``.claude/model-routing.log`` whenever the session calls the subagent tool
(``Agent``/``Task``). Nothing is injected into context and nothing is blocked — routing
switches are visible in the log, so the model never has to narrate them. A system message
is emitted to the user interface (not model context) to make each delegation — and the
model it runs on — visible in the console. When the routed agent's task kinds fall outside
the active role's row (§10.2, C20), an advisory line is appended.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

from claude_adapter import load_payload, print_result
from hook_core import HookResult, akmon_root, find_project_root

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools" / "model_routing"))

import routing


def _load_config(root: Path) -> dict:
    path = root / routing.LOCAL_CONFIG_REL
    if not path.is_file():
        return {}
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return config if isinstance(config, dict) else {}


def _format_system_message(line: str) -> str:
    """Format a delegation-log TSV line as a user-facing system message."""
    parts = [field.strip() if field.strip() != "-" else None for field in line.split("\t")]
    subagent = parts[2] if len(parts) > 2 else None
    model = parts[3] if len(parts) > 3 else None
    zone = parts[4] if len(parts) > 4 else None
    description = parts[5] if len(parts) > 5 else None

    msg = f"[akmon] → {subagent}"
    if model:
        msg += f" ({model})"
    if zone:
        msg += f" [{zone}]"
    if description:
        msg += f": {description}"
    return msg


def main() -> int:
    # Never block a tool call: on any failure, log to stderr and exit cleanly.
    try:
        payload = load_payload()
        tool_input = payload.get("tool_input") if isinstance(payload.get("tool_input"), dict) else {}
        timestamp = time.strftime("%Y-%m-%dT%H:%M:%S%z")
        session_id = payload.get("session_id")
        cwd = payload.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        root = find_project_root(Path(cwd))

        # Derive the model the agent is pinned to (its frontmatter `model:` isn't echoed in
        # the call), so the console line and record name the real model, not a bare `-`.
        config = _load_config(root)
        subagent_type = str(tool_input.get("subagent_type") or "")
        bound_model = routing.bound_model_for(config, subagent_type)

        line = routing.delegation_log_line(
            str(payload.get("tool_name") or ""),
            tool_input,
            timestamp,
            session_id if isinstance(session_id, str) else None,
            bound_model,
        )
        if line is not None:
            log_path = root / routing.DELEGATION_LOG_REL
            log_path.parent.mkdir(parents=True, exist_ok=True)
            with log_path.open("a", encoding="utf-8") as handle:
                handle.write(line + "\n")
            # Emit system message for UI visibility (zero token cost).
            messages = [_format_system_message(line)]
            # C20 — advise when the routed agent is outside the active role's task-kind row.
            registry = routing.load_registry(akmon_root(root), root)
            role = routing.active_role(payload.get("transcript_path"))
            warning = routing.role_matrix_warning(registry, subagent_type, role)
            if warning:
                messages.append(f"[akmon] ⚠ {warning}")
            print_result(HookResult(event_name="PreToolUse", system_message="\n".join(messages)))
    except Exception as exc:
        print(f"akmon delegation-log hook: {type(exc).__name__}: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
