#!/usr/bin/env python3
# Generated by _aitna/akmon/bin/sync.py. Do not edit this file by hand.
"""Claude wrapper for akmon model routing — orchestrator detection + status line.

Runs on **SessionStart** and **UserPromptSubmit**. Both read the session transcript
(``transcript_path`` in the payload) to detect the model the main chain is actually
running on, map it to an alias, and — when it differs from the recorded orchestrator (a
session launched on another model, or a mid-session ``/model`` switch) — recompute the
binding and regenerate the ``k-*`` subagent definitions so delegates follow the live
model. The orchestrator itself is never overridden: it is the owner's explicit choice,
only *detected* here.

- **SessionStart:** fresh config → status line (binding + self-check, plus the corridor
  warning when the orchestrator sits below the floor or on the reserved top rung).
  Missing/stale config → the init instruction (the one-time setup that records
  ``available`` + the second-opinion opt-in).
- **UserPromptSubmit:** silent unless the orchestrator changed — then a one-line notice
  naming the recomputed binding (plus the corridor warning when the switch left the
  healthy range) — or the context fill crossed a warn band (design §12).

Owner-addressed output — the init instruction, corridor and context-pressure warnings,
the rebind notice — goes out on **two channels** (requirement 11): ``additionalContext``
(the model acts on it) and ``systemMessage`` (the owner sees it in the host UI). The
steady-state status line stays context-only.

Logic lives in ``tools/model_routing/routing.py``; this entrypoint only adapts the payload.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from claude_adapter import load_payload, print_result
from hook_core import (
    HookResult,
    aitna_root_name,
    akmon_root,
    d2_pending_count,
    d2_status_line,
    d2_tracking_active,
    find_project_root,
)

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools" / "model_routing"))

import routing


def _settings_model(project_root: Path) -> str | None:
    for name in ("settings.local.json", "settings.json"):
        path = project_root / ".claude" / name
        if not path.is_file():
            continue
        try:
            settings = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        model = settings.get("model") if isinstance(settings, dict) else None
        if isinstance(model, str) and model:
            return model
    return None


def _load_config(root: Path) -> dict:
    config_path = root / routing.LOCAL_CONFIG_REL
    if not config_path.is_file():
        return {}
    try:
        loaded = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return loaded if isinstance(loaded, dict) else {}


def model_routing_result(root: Path, payload: dict) -> HookResult | None:
    akmon = akmon_root(root)
    if not routing.registry_path(akmon).is_file():
        return None  # akmon without model routing (older pin) — stay silent

    registry = routing.load_registry(akmon, root)
    config = _load_config(root)
    event = payload.get("hook_event_name") or "SessionStart"

    # Detect the model the main chain actually runs on (authoritative over settings) and
    # rebind the subagents when it moved. Needs an existing config for the `available`
    # ladder + opt-ins; first-time setup stays explicit (the init instruction below).
    detected = routing.detect_orchestrator(payload.get("transcript_path"), config.get("available"))
    rebound = bool(detected and config and detected != config.get("orchestrator"))
    if rebound:
        routing.rebind_to(root, registry, config, detected)
        config = _load_config(root)  # reload the freshly-written binding

    pressure = routing.context_pressure_notice(
        registry, payload.get("transcript_path"), payload.get("session_id")
    )

    aitna = aitna_root_name()
    if event != "SessionStart":
        # Per-turn: silent unless a switch or a pressure-band crossing just landed — zero
        # token cost otherwise. Both are owner-addressed → dual-channel (requirement 11).
        lines = (routing.rebind_notice(config, registry) if rebound else []) + pressure
        if not lines:
            return None
        text = "\n".join(lines)
        return HookResult(event_name=event, additional_context=text, system_message=text)

    # SessionStart: the transcript (when it named a model) is ground truth, so suppress the
    # weaker settings-model staleness signal once we have detected + bound to it.
    settings_model = None if detected else _settings_model(root)
    reason = routing.staleness(config, registry, settings_model)
    if reason is not None:
        lines = routing.init_instruction(reason, aitna) + pressure
        return HookResult(
            event_name="SessionStart",
            additional_context="\n".join(lines),
            system_message="\n".join([lines[0], *pressure]),
        )
    lines = routing.status_lines(config, registry, aitna) + pressure
    # Owner-addressed subset: warnings (corridor/pressure) and the fact of a rebind; the
    # steady-state status line itself stays context-only so the UI is quiet when healthy.
    owner = [line for line in lines if line.startswith("⚠")]
    if rebound:
        owner.insert(0, routing.rebind_notice(config, registry)[0])
    # D2 ledger counter (phase 3 of C11): appended to the status block when tracking is in use;
    # owner-addressed only when there are pending points to verify.
    if d2_tracking_active(root):
        d2_count = d2_pending_count(root)
        d2_line = d2_status_line(d2_count)
        lines.append(d2_line)
        if d2_count > 0:
            owner.append(d2_line)
    return HookResult(
        event_name="SessionStart",
        additional_context="\n".join(lines),
        system_message="\n".join(owner) if owner else None,
    )


def _project_root(payload: dict) -> Path:
    cwd = payload.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    return find_project_root(Path(cwd))


def main() -> int:
    # Never block a turn: on any failure, log to stderr and exit cleanly.
    try:
        payload = load_payload()
        print_result(model_routing_result(_project_root(payload), payload))
    except Exception as exc:
        print(f"akmon model-routing hook: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
