#!/usr/bin/env python3
# Generated by _aitna/akmon/bin/sync.py. Do not edit this file by hand.
"""Claude SessionStart wrapper for the akmon active-agent reminder.

The reminder logic lives in ``hook_core.py`` and returns a vendor-neutral ``HookResult``.
This entrypoint only adapts Claude Code's JSON payload/output shape so existing
``.claude/settings.json`` wiring can keep pointing here.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from claude_adapter import load_payload, print_result
from hook_core import session_start_result


def _project_root(payload: dict) -> Path:
    cwd = payload.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    return Path(cwd)


def main() -> int:
    # Never block session start: on any failure, log to stderr (diagnostic, not the hook's
    # JSON stdout) and exit cleanly.
    try:
        print_result(session_start_result(_project_root(load_payload())))
    except Exception as exc:
        print(f"akmon session-start-agent hook: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
